### ISSUE TITLE
`/Product/:entityId/productAssets` ignores language header

### ISSUE THREAD

**Issue by marcus-at-localhost** [atrocore/atropim#524]
Using this Endpoint for the first time (in PIM 1.9.34) it behaves not as expected:

`select` fields and sending language header returns `null`
![image](https://github.com/atrocore/atropim/assets/1337223/87c8c66d-0723-4aa1-9299-07377621fd44)

`select` fields and not sending language header returns standard language (I think that's expected)
![image](https://github.com/atrocore/atropim/assets/1337223/b2bb2066-b9aa-4419-9dc6-7cbab022c4b4)

No `select` fields and no language header returns all languages (that is expected)
![image](https://github.com/atrocore/atropim/assets/1337223/85c90365-2394-4f0a-b4bc-eeaaa6857632)

No `select` fields and sending language header returns `null`
![image](https://github.com/atrocore/atropim/assets/1337223/6181b5c4-676a-49d5-beda-ffcec7e261c4)

Edit:
Tested the `/Asset` Endpoint querying that one product, behaves as expected:
![image](https://github.com/atrocore/atropim/assets/1337223/ffd4eb73-c2d6-458d-a001-1ce9cfdfaa99)

## Expectation

if sending language header, then `select=asset_description,*` returns the correct language version as `{"access_description":"Localized Value"}` (like the other endpoints unless that behavior changed).

**Comment by rratsun** [comment]
ok. I have created an internal issue for it.

**Comment by rratsun** [comment]
The issue is not relevant anymore. For getting product assets please use /Product/:entityId/assets endpoint.
/Product/:entityId/productAssets - does not exists in the latest releases. 
We dicided to remove entity of type Relationship. Instead of this all ManyToMany relations is also an entity of type Relation ( /ProductAsset). Relation entity can has additional fields, but in the same time it is a relationship.
